"""A whole tinygrad computation as one DSP program: every kernel in order, one FastRPC call on the phone (or one hexagon-sim run).

  calls, bufs = capture(fn)                      run fn() (it realizes something) with every kernel recorded, not executed
  info = emit(outdir, calls, bufs, inp, out)     k<n>.c per distinct kernel + graph.h (buffers, constants blob, call order) + blob.bin
  y, cycles = run_sim(outdir, x_bytes, n_out)    the program on hexagon-sim -mv69 --mhmx 1 (per-call pcycles in sim_profile.txt)
  build_skel(outdir)                             the FastRPC skel + Android client (needs HEXAGON_SDK_ROOT, HEXAGON_TOOLCHAIN, an NDK)

Kernels are captured under DEV=DSP MOCKDSP=1 (qemu can't run HMX, so nothing runs): sources, the buffers each call reads and
writes, and the contents of every buffer read before any kernel writes it (weights, constants) -- those become the blob. The
input buffer is filled per inference, the output read back. HMX kernels share one VTCM tile pool: build them all with the same
HMX_VTCM_KB (graph.h carries it; the skel acquires that much).
"""
from __future__ import annotations
import os, re, pathlib, subprocess
from typing import Callable

FILES = pathlib.Path(__file__).parent / "dsp_graph_files"
_CAP: dict = {"calls": [], "bufs": {}}  # mutated in place: pattern functions snapshot their globals (no rebinding)

def _cap_exec(ctx, call, ast):
  import tinygrad.engine.realize as R
  resolved = R.resolve_params(call, ctx.input_uops)
  ids = []
  for i in ast.arg.globals:
    b = resolved[i].buffer
    if id(b) not in _CAP["bufs"]: _CAP["bufs"][id(b)] = [b, b.nbytes, None]
    ids.append(id(b))
  outs = {ast.arg.globals.index(i) for i in ast.arg.outs}
  src = ast.src[2].arg
  if "__hmx_qadd_chunk(" in src: outs.add(0)  # the custom QLinearAdd kernel writes its output in the CUSTOM call, not a STORE
  _CAP["calls"].append((re.sub(r"\x1b\[[0-9;]*m", "", ast.arg.name), src, ids, outs))
  return [0.0]

def capture(fn:Callable[[], object]) -> tuple[list, dict]:
  """fn's kernels, in order, recorded instead of run -> (calls, bufs): calls = [(name, src, [buffer ids], output param
  indices)], bufs = {id: [Buffer, nbytes, "read" if read before any kernel writes it]}. Realize constants before."""
  import tinygrad.engine.realize as R
  from tinygrad.uop.ops import PatternMatcher
  _CAP["calls"].clear(); _CAP["bufs"].clear()
  pats = [(p, _cap_exec if f is R.exec_kernel else f) for p, f in R.pm_exec.patterns]
  old, R.pm_exec = R.pm_exec, PatternMatcher(pats)
  try: fn()
  finally: R.pm_exec = old
  calls, bufs = list(_CAP["calls"]), dict(_CAP["bufs"])
  written: set[int] = set()
  for _, _, ids, outs in calls:
    for j, b in enumerate(ids):
      if j in outs: written.add(b)
      elif b not in written and bufs[b][2] is None: bufs[b][2] = "read"
  return calls, bufs

def emit(outdir, calls, bufs, inp, out) -> dict:
  """calls/bufs (capture) as C in outdir; inp, out: the input / output Buffers"""
  from tinygrad.helpers import getenv
  o = pathlib.Path(outdir); o.mkdir(parents=True, exist_ok=True)
  xid, yid = id(inp), id(out)
  order = list(dict.fromkeys(b for _, _, ids, _ in calls for b in ids))
  idx = {b: i for i, b in enumerate(order)}
  blob, off = bytearray(), {}
  for b in order:
    if bufs[b][2] == "read" and b != xid:
      off[b] = len(blob); blob += bytes(bufs[b][0].as_memoryview())
      blob += bytes(-len(blob) % 128)
  knames: dict[str, str] = {}
  lines: list[str] = []
  for name, src, ids, _ in calls:
    if src not in knames:
      kn = knames[src] = f"k{len(knames)}"
      body = src.split("/* DSP boilerplate */")[0]
      m = re.search(r"noinline\)\) void\s+(\w+)\(", body) or re.search(r"\bvoid\s+(\w+)\(unsigned char\*", body)
      body = re.sub(rf"\bvoid\s+{re.escape(m.group(1))}\(", f"void {kn}(", body, count=1)
      (o / f"{kn}.c").write_text(body)
    lines.append(f"  {knames[src]}({', '.join(f'B[{idx[b]}]' for b in ids)}); G_PROF({len(lines)});  /* {name} */")
  rnd = lambda n: (n + 127) // 128 * 128 + 128  # + 128: slack for the HMX A packer's unaligned row loads
  h = [f"/* generated by tinygrad/runtime/support/dsp_graph.py: {len(calls)} kernel calls, {len(knames)} distinct kernels, {len(order)} buffers */",
       f"#define G_NBUF {len(order)}", f"#define G_INPUT {idx[xid]}", f"#define G_OUTPUT {idx[yid]}", f"#define G_BLOB_BYTES {len(blob)}",
       f"#define G_VTCM_KB {int(getenv('HMX_VTCM_KB', 256))}",
       "static const unsigned G_BYTES[G_NBUF] = {" + ", ".join(str(rnd(bufs[b][1])) for b in order) + "};",
       "static const int G_OFF[G_NBUF] = {" + ", ".join(str(off.get(b, -1)) for b in order) + "};",
       *[f"void {k}();" for k in knames.values()],
       "#ifndef G_PROF\n#define G_PROF(i)\n#endif  /* per-call timing hook: G_PROF(call index) after each call */",
       "static void g_run(unsigned char** B) {", *lines, "}"]
  (o / "graph.h").write_text("\n".join(h) + "\n")
  (o / "blob.bin").write_bytes(bytes(blob))
  return {"kernels": list(knames.values()), "nbuf": len(order), "blob": len(blob), "calls": len(calls),
          "scratch": sum(rnd(bufs[b][1]) for b in order if b not in off)}

SIM_MAIN = r"""#include <stdio.h>
#include <stdlib.h>
#include <string.h>
extern unsigned long long hexagon_sim_read_pcycles(void);
static unsigned long long g_prof[512], g_last;
#define G_PROF(i) (g_prof[i] += hexagon_sim_read_pcycles() - g_last, g_last = hexagon_sim_read_pcycles())
#include "graph.h"
unsigned char* __hmx_vtcm;
unsigned int __hmx_gen = 1;
static void rd(const char* p, void* d, unsigned n) { FILE* f = fopen(p, "rb"); if (!f || fread(d, 1, n, f) != n) { printf("read %s\n", p); exit(1); } fclose(f); }
int main(int argc, char** argv) {
  int reps = argc > 1 ? atoi(argv[1]) : 1;
  unsigned base; __asm__ volatile("%0 = cfgbase" : "=r"(base));
  __hmx_vtcm = (unsigned char*)(*(volatile unsigned*)((base << 16) + 0x38) << 16);  /* VTCM base from the config table */
  unsigned r; __asm__ volatile("%0 = ssr" : "=r"(r)); r |= 1u << 26; __asm__ volatile("ssr = %0; isync" :: "r"(r));
  unsigned char* blob = aligned_alloc(128, G_BLOB_BYTES + 128);
  rd("blob.bin", blob, G_BLOB_BYTES);
  unsigned char* B[G_NBUF];
  for (int i = 0; i < G_NBUF; i++) {
    B[i] = aligned_alloc(128, G_BYTES[i]);
    if (G_OFF[i] >= 0) memcpy(B[i], blob + G_OFF[i], G_BYTES[i]); else memset(B[i], 0, G_BYTES[i]);
  }
  rd("input.bin", B[G_INPUT], INPUT_BYTES);
  unsigned long long t0 = hexagon_sim_read_pcycles();
  for (int i = 0; i < reps; i++) { g_last = hexagon_sim_read_pcycles(); g_run(B); }
  unsigned long long t1 = hexagon_sim_read_pcycles();
  FILE* f = fopen("out.bin", "wb"); fwrite(B[G_OUTPUT], 1, OUTPUT_BYTES, f); fclose(f);
  printf("graph pcycles %llu\n", (t1 - t0) / reps);
  for (int i = 0; i < 512 && g_prof[i]; i++) printf("call %d pcycles %llu\n", i, g_prof[i] / reps);
  return 0;
}
"""

def _tools() -> pathlib.Path:
  return pathlib.Path(os.environ.get("HEXAGON_TOOLS", os.path.expanduser("~/.cache/hexagon-oa-19/Tools")))

def run_sim(outdir, x_bytes:bytes, y_nbytes:int, reps:int=1) -> tuple[bytes, int]:
  """the emitted program on hexagon-sim with input x_bytes -> (the output's first y_nbytes, pcycles per inference)"""
  from tinygrad.runtime import ops_dsp
  o, t = pathlib.Path(outdir), _tools()
  (o / "input.bin").write_bytes(x_bytes)
  (o / "sim_main.c").write_text(f"#define INPUT_BYTES {len(x_bytes)}\n#define OUTPUT_BYTES {y_nbytes}\n" + SIM_MAIN)
  ks = sorted(p.name for p in o.glob("k*.c"))
  subprocess.run([str(t / "bin/hexagon-clang"), "-mv69", "-mhmx", "-mhvx", "-mhvx-length=128B", "-O2", "-Wno-deprecated-non-prototype",
                  "sim_main.c", *ks, "-o", "g.elf", "-lhexagon"], cwd=o, check=True)
  r = subprocess.run([str(t / "bin/hexagon-sim"), "-mv69", "--mhmx", "1", "--timing", "g.elf", "--", str(reps)], cwd=o,
                     env=ops_dsp._hexsim_env(t, o), capture_output=True, text=True, check=True)
  (o / "sim_profile.txt").write_text(r.stdout)
  return (o / "out.bin").read_bytes(), int(re.search(r"graph pcycles (\d+)", r.stdout).group(1))

def build_skel(outdir, jobs:int=4) -> tuple[pathlib.Path, pathlib.Path]:
  """the FastRPC skel (tg_hmx_rpc.so) + Android client for the emitted program. Needs HEXAGON_SDK_ROOT, HEXAGON_TOOLCHAIN
  (a -mhmx toolchain) and an NDK clang (NDK_CLANG). Run on the phone: client 'file:///tg_hmx_rpc.so?tg_hmx_rpc_skel_handle_invoke
  &_modver=1.0&_dom=cdsp' <case dir with a.bin (input), b.bin (blob.bin), ref.bin> [iters], ADSP_LIBRARY_PATH at the skel"""
  import shutil
  from concurrent.futures import ThreadPoolExecutor
  o, sdk, tc = pathlib.Path(outdir), pathlib.Path(os.environ["HEXAGON_SDK_ROOT"]), pathlib.Path(os.environ["HEXAGON_TOOLCHAIN"])
  ndk = os.environ.get("NDK_CLANG", "/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang")
  for f in ("skel.c", "client.c", "hmx_runtime.h", "tg_hmx_rpc.idl"): shutil.copy(FILES / f, o / f)
  arch = "v69"
  inc = ["-I", ".", "-I", str(sdk / "incs"), "-I", str(sdk / "incs/stddef")]
  qurt = ["-I", str(sdk / f"rtos/qurt/compute{arch}/include/qurt"), "-I", str(sdk / f"rtos/qurt/compute{arch}/include/posix")]
  hc = [str(tc / "bin/hexagon-clang"), "-c", "-O2", "-fPIC", f"-mcpu=hexagon{arch}", f"-mhvx={arch}", "-mhvx-length=128b", "-mhmx"]
  run = lambda cmd: subprocess.run(cmd, cwd=o, check=True)
  run([str(sdk / "ipc/fastrpc/qaic/Ubuntu/qaic"), "-I", str(sdk / "incs"), "-I", str(sdk / "incs/stddef"), "tg_hmx_rpc.idl"])
  run([str(tc / "bin/hexagon-clang"), "-c", "-O2", "-fPIC", f"-mcpu=hexagon{arch}", *inc, "-o", "skel_rpc.o", "tg_hmx_rpc_skel.c"])
  run([*hc, *inc, *qurt, "-o", "impl.o", "skel.c"])
  ks = sorted(p.name for p in o.glob("k*.c"))
  with ThreadPoolExecutor(jobs) as ex: list(ex.map(lambda k: run([*hc, "-Wno-deprecated-non-prototype", "-o", k[:-2] + ".o", k]), ks))
  lib = tc / f"target/hexagon/lib/{arch}/G0"
  run([str(tc / "bin/hexagon-link"), "-Bdynamic", "-shared", "-export-dynamic", "-o", "tg_hmx_rpc.so", "skel_rpc.o", "impl.o",
       *[k[:-2] + ".o" for k in ks], str(lib / "pic/libgcc.a"), str(lib / "pic/libgcc.so")])
  run([ndk, "-O2", *inc, "-I", str(sdk / "ipc/fastrpc/rpcmem/inc"), "-o", "client", "client.c", "tg_hmx_rpc_stub.c",
       "-L", str(sdk / "ipc/fastrpc/remote/ship/android_aarch64"), "-lcdsprpc"])
  return o / "tg_hmx_rpc.so", o / "client"
