"""A captured tinygrad graph as one standalone Hexagon v65 program: the SDM845 cDSP's path (integer-only HVX, scalar float,
four hardware threads). dsp_graph.py is the v69 / HMX sibling; this one shares its capture() and differs in what it emits:

  calls, bufs = dsp_graph.capture(lambda: jit(**inputs))     every kernel recorded, not run (MOCKDSP=1). A TinyJit replay works:
                                                             its memory plan (views into one arena) is kept, not re-allocated
  info = emit(outdir, calls, bufs, [input Buffers], output)  k<n>.c per distinct kernel + graph.h + blob.bin (the weights)
  y = run_qemu(outdir, x_bytes)                              the whole program under qemu-hexagon, no phone needed
  build(outdir)                                              FastRPC skel (tg_graph.so) + Android client

Buffers are laid out as regions, one per base Buffer: a view becomes (region, byte offset), so kernels that alias one arena
through different views (a BITCAST of a float arena read as half, say) still see one memory. Regions no kernel writes are the
blob, uploaded once in chunks and read in place; the rest are allocated once and zeroed. A DSP_THREADS kernel (a trailing
core_id) runs its slices on a qurt thread pool on the phone, serially under qemu.
"""
from __future__ import annotations
import os, re, pathlib, subprocess, shutil

FILES = pathlib.Path(__file__).parent / "dsp_graph_files" / "v65"
ALIGN = 128
def _rnd(n:int) -> int: return (n + ALIGN - 1) // ALIGN * ALIGN + ALIGN  # + ALIGN: a final HVX load may run past the end

def emit(outdir, calls, bufs, inputs:list, output) -> dict:
  """calls/bufs from dsp_graph.capture; inputs: the graph's input Buffers in order, output: its output Buffer"""
  o = pathlib.Path(outdir); o.mkdir(parents=True, exist_ok=True)
  for p in o.glob("k*.c"): p.unlink()
  views = {i: v[0] for i, v in bufs.items()}
  base = {i: b.base for i, b in views.items()}
  regions: list = list(dict.fromkeys(base[i] for _, _, ids, *_ in calls for i in ids))
  rid = {id(r): n for n, r in enumerate(regions)}
  written = {id(base[b]) for _, _, ids, outs, _ in calls for j, b in enumerate(ids) if j in outs}
  in_ids, out_id = [id(x.base) for x in inputs], id(output.base)
  for x in inputs:
    if x.offset != 0 or x.nbytes != x.base.nbytes: raise ValueError("a graph input must be a whole buffer")
  missing = [n for n in [*in_ids, out_id] if n not in rid]
  if missing: raise ValueError(f"{len(missing)} graph input/output buffers are not used by any captured kernel")
  blob, blob_off = bytearray(), {}
  for r in regions:
    if id(r) in written or id(r) in in_ids: continue
    blob_off[id(r)] = len(blob)
    blob += bytes(r.as_memoryview()) + bytes(-r.nbytes % ALIGN)

  knames: dict[str, str] = {}
  thunks, cases = [], []
  for n, (name, src, ids, _, nthreads) in enumerate(calls):
    if src not in knames:
      kn = knames[src] = f"k{len(knames)}"
      body = src.split("/* DSP boilerplate */")[0]
      m = re.search(r"noinline\)\) void\s+(\w+)\(", body)
      if m is None: raise ValueError(f"no kernel function in {name}")
      (o / f"{kn}.c").write_text(re.sub(rf"\bvoid\s+{re.escape(m.group(1))}\(", f"void {kn}(", body, count=1))
    args = ", ".join(f"R[{rid[id(base[b])]}]+{views[b].offset}" for b in ids)
    if nthreads:
      thunks.append(f"static void g_t{n}(unsigned char** R, int core) {{ {knames[src]}({args}, core); }}")
      cases.append(f"  case {n}: G_PARALLEL(g_t{n}, R, {nthreads}); break;  /* {name} */")
    else: cases.append(f"  case {n}: {knames[src]}({args}); break;  /* {name} */")
  out_view = output
  h = [f"/* generated by tinygrad/runtime/support/dsp_graph_v65.py: {len(calls)} calls, {len(knames)} kernels, {len(regions)} regions */",
       f"#define G_NCALLS {len(calls)}", f"#define G_NREG {len(regions)}", f"#define G_BLOB_BYTES {len(blob)}",
       f"#define G_NIN {len(inputs)}", f"#define G_OUT_REG {rid[out_id]}", f"#define G_OUT_OFF {out_view.offset}",
       f"#define G_OUT_BYTES {out_view.nbytes}",
       "static const unsigned G_REG_BYTES[G_NREG] = {" + ", ".join(str(_rnd(r.nbytes)) for r in regions) + "};",
       "static const int G_REG_BLOB[G_NREG] = {" + ", ".join(str(blob_off.get(id(r), -1)) for r in regions) + "};",
       "static const int G_IN_REG[G_NIN] = {" + ", ".join(str(rid[i]) for i in in_ids) + "};",
       "static const unsigned G_IN_BYTES[G_NIN] = {" + ", ".join(str(x.nbytes) for x in inputs) + "};",
       *[f"void {k}();" for k in knames.values()],
       "#ifndef G_PARALLEL\n#define G_PARALLEL(f, R, n) for (int _c = 0; _c < (n); _c++) f(R, _c)\n#endif",
       *thunks,
       "static void g_call(int i, unsigned char** R) {", "  switch (i) {", *cases, "  }", "}"]
  (o / "graph.h").write_text("\n".join(h) + "\n")
  (o / "blob.bin").write_bytes(bytes(blob))
  return {"calls": len(calls), "kernels": len(knames), "regions": len(regions), "blob": len(blob),
          "threaded_calls": sum(1 for c in calls if c[4]), "input_bytes": [x.nbytes for x in inputs], "output_bytes": out_view.nbytes,
          "scratch": sum(_rnd(r.nbytes) for r in regions if id(r) not in blob_off)}

def _input_blob(xs:list[bytes]) -> bytes:
  return b"".join(x + bytes(-len(x) % ALIGN) for x in xs)  # inputs packed back to back, each 128-byte aligned

def _cc() -> str: return os.environ.get("CC", "clang")
def _hvx_args(arch:str="v65") -> list[str]: return ["--target=hexagon", f"-mcpu=hexagon{arch}", f"-mhvx={arch}", "-mhvx-length=128b"]

QEMU_MAIN = r"""
#include "graph.h"
static unsigned char* R[G_NREG];
static void rd(void* d, unsigned n) { for (unsigned r = 0; r < n; ) { int k = read(0, (unsigned char*)d + r, n - r); if (k <= 0) exit(2); r += k; } }
void _start(void) {
  unsigned char* blob = mmap2(0, G_BLOB_BYTES + 4096, 3, 0x21, -1, 0);
  rd(blob, G_BLOB_BYTES);
  for (int i = 0; i < G_NREG; i++) R[i] = G_REG_BLOB[i] >= 0 ? blob + G_REG_BLOB[i] : mmap2(0, G_REG_BYTES[i] + 4096, 3, 0x21, -1, 0);
  for (int i = 0; i < G_NIN; i++) { rd(R[G_IN_REG[i]], G_IN_BYTES[i]); if (G_IN_BYTES[i] % 128) { unsigned char pad[128]; rd(pad, 128 - G_IN_BYTES[i] % 128); } }
  for (int i = 0; i < G_NCALLS; i++) g_call(i, R);
  write(1, R[G_OUT_REG] + G_OUT_OFF, G_OUT_BYTES);
  exit(0);
}
"""

def run_qemu(outdir, xs:list[bytes], timeout:int=3600) -> bytes:
  """the emitted program under qemu-hexagon-static (DSP_THREADS slices run in turn) -> the output bytes"""
  from tinygrad.runtime import ops_dsp
  from concurrent.futures import ThreadPoolExecutor
  o = pathlib.Path(outdir)
  boiler = ops_dsp.mockdsp_boilerplate.replace("{{", "{").replace("}}", "}")
  (o / "qemu_main.c").write_text(boiler + "\n" + QEMU_MAIN)
  flags = [*_hvx_args(), "-O2", "-fPIC", "-ffreestanding", "-nostdlib", "-fno-stack-protector", "-Wno-deprecated-non-prototype"]
  ks = sorted(p.name for p in o.glob("k*.c"))
  run = lambda cmd: subprocess.run(cmd, cwd=o, check=True)
  with ThreadPoolExecutor(os.cpu_count()) as ex: list(ex.map(lambda k: run([_cc(), "-c", *flags, "-o", f"q_{k[:-2]}.o", k]), ks))
  libgcc = ops_dsp._find_libgcc()
  run([_cc(), "-static", "-fuse-ld=lld", *flags, "-o", "graph_qemu.elf", "qemu_main.c", *[f"q_{k[:-2]}.o" for k in ks],
       *([libgcc] if libgcc else [])])
  stdin = (o / "blob.bin").read_bytes() + _input_blob(xs)
  return subprocess.run(["qemu-hexagon-static", str(o / "graph_qemu.elf")], input=stdin, stdout=subprocess.PIPE, check=True,
                        timeout=timeout).stdout

def build(outdir, skel_arch:str="v68", kernel_arch:str="v65", jobs:int=8) -> tuple[pathlib.Path, pathlib.Path]:
  """the FastRPC skel (tg_graph.so) + Android client. The kernels are built for kernel_arch with $CC (a v65-capable clang; the
  Hexagon SDK 6.x compiler starts at v68); the skel for skel_arch with the SDK's. Needs HEXAGON_SDK_ROOT, HEXAGON_TOOLCHAIN and an
  NDK clang (NDK_CLANG). On the phone: client 'file:///tg_graph.so?tg_graph_skel_handle_invoke&_modver=1.0&_dom=cdsp' <dir with
  blob.bin input.bin ref.bin> [iters] [threads] [batch] [prof], ADSP_LIBRARY_PATH at the skel"""
  from concurrent.futures import ThreadPoolExecutor
  o, sdk, tc = pathlib.Path(outdir), pathlib.Path(os.environ["HEXAGON_SDK_ROOT"]), pathlib.Path(os.environ["HEXAGON_TOOLCHAIN"])
  ndk = os.environ.get("NDK_CLANG", "/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang")
  for f in ("skel.c", "client.c", "tg_graph.idl"): shutil.copy(FILES / f, o / f)
  inc = ["-I", ".", "-I", str(sdk / "incs"), "-I", str(sdk / "incs/stddef")]
  qurt = ["-I", str(sdk / f"rtos/qurt/compute{skel_arch}/include/qurt"), "-I", str(sdk / f"rtos/qurt/compute{skel_arch}/include/posix")]
  run = lambda cmd: subprocess.run(cmd, cwd=o, check=True)
  run([str(sdk / "ipc/fastrpc/qaic/Ubuntu/qaic"), "-I", str(sdk / "incs"), "-I", str(sdk / "incs/stddef"), "tg_graph.idl"])
  hc = [str(tc / "bin/hexagon-clang"), "-c", "-O2", "-fPIC", f"-mcpu=hexagon{skel_arch}"]
  run([*hc, *inc, "-o", "skel_rpc.o", "tg_graph_skel.c"])
  run([*hc, f"-mhvx={skel_arch}", "-mhvx-length=128b", "-Wno-deprecated-non-prototype", *inc, *qurt, "-o", "impl.o", "skel.c"])
  ks = sorted(p.name for p in o.glob("k*.c"))
  kflags = [*_hvx_args(kernel_arch), "-O2", "-fPIC", "-ffreestanding", "-nostdlib", "-fno-stack-protector", "-Wno-deprecated-non-prototype"]
  with ThreadPoolExecutor(jobs) as ex: list(ex.map(lambda k: run([_cc(), "-c", *kflags, "-o", k[:-2] + ".o", k]), ks))
  lib = tc / f"target/hexagon/lib/{skel_arch}/G0"
  run([str(tc / "bin/hexagon-link"), "-Bdynamic", "-shared", "-export-dynamic", "-o", "tg_graph.so", "skel_rpc.o", "impl.o",
       *[k[:-2] + ".o" for k in ks], str(lib / "pic/libgcc.a"), str(lib / "pic/libgcc.so")])
  run([ndk, "-O2", *inc, "-o", "client", "client.c", "tg_graph_stub.c", "-L", str(sdk / "ipc/fastrpc/remote/ship/android_aarch64"),
       "-lcdsprpc"])
  return o / "tg_graph.so", o / "client"

def write_case(outdir, xs:list[bytes], ref:bytes) -> None:
  """input.bin (the inputs as the client sends them) and ref.bin (the expected output) next to blob.bin"""
  o = pathlib.Path(outdir)
  (o / "input.bin").write_bytes(_input_blob(xs))
  (o / "ref.bin").write_bytes(ref)
